# /docker-compose.yml
version: "3"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - service.forex.base_uri=http://one-frame:8080
    depends_on:
      - one-frame
  one-frame:
    image: paidyinc/one-frame:latest
    ports:
      - "8085:8080"
